### ISSUE TITLE
User Signup

### ISSUE THREAD

**Issue by Damilola27** [everybees/wallet#1]
For a user to signup, collect their basic info and create an object of User.

**Comment by Yetife** [comment]
I will like to work on this.

**Comment by Yetife** [comment]
I am having migrations issues:

 "POST /accounts/users/signup HTTP/1.1" 400 118

**Comment by everybees** [comment]
> I am having migrations issues:
> 
> "POST /accounts/users/signup HTTP/1.1" 400 118

Have you tried "python manage.py runserver"?

**Comment by Toska29** [comment]
> I am having migrations issues:
> 
> "POST /accounts/users/signup HTTP/1.1" 400 118

oh yeah
